services:
  - type: web
    name: consultorio-psicologia
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT wsgi:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: consultorio-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false

  - type: pserv
    name: consultorio-db
    databaseName: consultorio_psicologia
    user: consultorio_user
    plan: free